- name: npm install and build
  run: |
    npm install
    npm run build
  env:
    MONGODB_URI: ${{ secrets.MONGODB_URI }}
    MONGODB_DB: ${{ secrets.MONGODB_DB }}
    JWT_SECRET: ${{ secrets.JWT_SECRET }}
    ACS_EMAIL_CONNECTION_STRING: ${{ secrets.ACS_EMAIL_CONNECTION_STRING }}
    ACS_EMAIL_SENDER: ${{ secrets.ACS_EMAIL_SENDER }}
    ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
    AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
    AZURE_STORAGE_CONTAINER: ${{ secrets.AZURE_STORAGE_CONTAINER }}
    NEXT_PUBLIC_APP_NAME: ${{ secrets.NEXT_PUBLIC_APP_NAME }}